### ISSUE TITLE
Team Week 4 - FRQ 1

### ISSUE THREAD

**Issue by samayasankuratri** [sarayu-pr11/teamGrapeSnails#2]
**Review Score: 3/3
Crossover Score: 2.7+/3
Self believed score: 3/3**

FRQ

- [x] [Sarayu Pochimireddy](https://github.com/sarayu-pr11/sarayucsa/issues/6)
- [x] [Iris Yang](https://github.com/iriisyang/Iris-Yang/issues/6#issue-1379625714)
- [x] [FRQ Lesson](https://sarayu-pr11.github.io/sarayucsa/markdown/2022/09/19/frqlesson.html)

2D Arrays

- [x] [Lesson Plan](https://samayass.github.io/samayaCSA/jupyter/2022/09/19/2d-lesson.html)
- [x] [Samaya Sankuratri](https://github.com/samayass/samayaCSA/issues/6)
- [x] [Alice Tang](https://github.com/tangalice/alicetang/issues/6)

**Comment by jm1021** [comment]
Lesson Format
Samaya/Alice - starts with def then initialization.  Discussed 0 counting.  Shared ij indexing.  Also, discuss print vs println.  Discussed forward and backwards.  Then went to Monkeys which made information much more clear.

Sarayu, Iris - Started talking about control structures ... IF then Case.    Then discussed loops and repeating until express is false.  Discussed requirements from College Board.   Used 2019 FRQ leap years.   Discussed counting leap years and then day of the week.

Very nice organization and presentation.  Hit on all expectation by me.

3.0 for everyone

**Comment by NathanManangan** [comment]
- [x] 2D arrays and data types, for loops vs horizontal
- [x] Printing out horizontally being different than printing vertically, changing row and column 
- [x] Printing out Monkey
- [x] Control Structures lessons
- [x] FRQ 2019 - kept repeating through for loop until leapYear and returnDay

Very clear with vocab, FRQ and how functions worked.
2.7+/3

**Comment by ellierozen** [comment]
- Explained different ways of creating 2d arrays and the differences between the horizontal vs vertical ++
- went through all of the terms for each of the frq and the 2d arrays 
-2.7 +

**Comment by B-G101** [comment]
2.7+/3
 - Group did a really nice job of explaining the functionality of their 2d array code
 - Explained each concept very nicely when discussing the FRQ
 - Talked about the terms and vocabulary for each
 - I liked the organization of their presentation and how each person was responsible for each section

**Comment by AadyaDaita** [comment]
2.7+/3

### 2D arrays:

- [x] The lesson was explained really well, with going over how to initialize 2D arrays
- [x] Went over what they did last week about 2D arrays

### FRQs 

- [x] were very detailed, and went over the answers. 
- [x] explained all the vocab in detail

**Comment by icyGS** [comment]
2.7+/3

Very nice lesson, explained all of the stuff used in the hacks, as well as the hacks themselves.

**Comment by dontran15** [comment]
## 2.7+/3
- Creating 2d arrays w/ different data types
- Printing horizontally vs. vertically using loops by changing the iteration order of column and row
- Method and control structures esp in the context of Collegeboard's expectations
- Well presented and easy and clear to follow
- Good way of presenting especially for learning

**Comment by shreya-ahujaa** [comment]
# Score: 2.7+
(2.7+ because they explain everything really well in an organized way)

## Two Dimensional Arrays
- The lesson was explained well, with extra notes about things that were not relating to the monkeys
- I like how they showed the examples with numbers, and then also showed it with the monkeys

## FRQ
- Went over all the requirements that Collegeboard wanted
- Went over each of the variables and each part of the code was very detailed

**Comment by NicholasRamos5** [comment]
Your lesson on college board was incredibly detailed and thouroughly elaborated the expected requirements. 
Explained 2d arrays and iteration. 
-2.7+
